// <auto-generated />
using System;
using InfraOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfraOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InfraOpsDbContext))]
    [Migration("20260518214819_AddPreventiveValidations")]
    partial class AddPreventiveValidations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId", "FieldKey")
                        .IsUnique();

                    b.ToTable("entity_field_definitions", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntityFieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("EntityFieldDefinitionId", "Value")
                        .IsUnique();

                    b.ToTable("entity_field_options", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("entity_types", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Inventory.Entities.InventoryAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityFieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("Id");

                    b.HasIndex("EntityFieldDefinitionId");

                    b.HasIndex("InventoryItemId", "FieldKey")
                        .IsUnique();

                    b.ToTable("inventory_attribute_values", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Inventory.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SiteId");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Locations.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.Locations.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityTypeCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InventoryItemDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreventiveTemplateCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("PreventiveTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreventiveTemplateName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PreventiveTemplateId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SiteId");

                    b.HasIndex("Status");

                    b.ToTable("preventive_executions", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PreventiveExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveExecutionId", "ItemKey")
                        .IsUnique();

                    b.ToTable("preventive_execution_answers", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("MaximumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("MinimumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("PreventiveExecutionTemplateSectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresCommentOnFailure")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresPhotoOnFailure")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceChecklistItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveExecutionTemplateSectionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("PreventiveExecutionTemplateSectionId", "ItemKey")
                        .IsUnique()
                        .HasDatabaseName("IX_preventive_execution_template_items_PreventiveExecutionTem~1");

                    b.ToTable("preventive_execution_template_items", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PreventiveExecutionTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveExecutionTemplateItemId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("PreventiveExecutionTemplateItemId", "Value")
                        .IsUnique()
                        .HasDatabaseName("IX_preventive_execution_template_options_PreventiveExecutionT~1");

                    b.ToTable("preventive_execution_template_options", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("PreventiveExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceTemplateSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveExecutionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("preventive_execution_template_sections", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveValidationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PreventiveExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValidatorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PreventiveExecutionId");

                    b.HasIndex("ValidatorUserId");

                    b.ToTable("preventive_validation_records", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("MaximumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("MinimumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("PreventiveTemplateSectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresCommentOnFailure")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresPhotoOnFailure")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveTemplateSectionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("PreventiveTemplateSectionId", "ItemKey")
                        .IsUnique();

                    b.ToTable("preventive_checklist_items", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveChecklistOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PreventiveChecklistItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveChecklistItemId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("PreventiveChecklistItemId", "Value")
                        .IsUnique();

                    b.ToTable("preventive_checklist_options", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EntityTypeId");

                    b.ToTable("preventive_templates", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PreventiveTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("PreventiveTemplateId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("preventive_template_sections", (string)null);
                });

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityFieldDefinition", b =>
                {
                    b.HasOne("InfraOps.Domain.EntityTypes.Entities.EntityType", null)
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityFieldOption", b =>
                {
                    b.HasOne("InfraOps.Domain.EntityTypes.Entities.EntityFieldDefinition", null)
                        .WithMany("Options")
                        .HasForeignKey("EntityFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("InfraOps.Domain.Identity.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("InfraOps.Domain.Identity.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfraOps.Domain.Identity.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("InfraOps.Domain.Identity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfraOps.Domain.Identity.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfraOps.Domain.Inventory.Entities.InventoryAttributeValue", b =>
                {
                    b.HasOne("InfraOps.Domain.EntityTypes.Entities.EntityFieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("EntityFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraOps.Domain.Inventory.Entities.InventoryItem", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("InfraOps.Domain.Inventory.Entities.InventoryItem", b =>
                {
                    b.HasOne("InfraOps.Domain.EntityTypes.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraOps.Domain.Locations.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraOps.Domain.Locations.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("Region");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("InfraOps.Domain.Locations.Entities.Site", b =>
                {
                    b.HasOne("InfraOps.Domain.Locations.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecution", b =>
                {
                    b.HasOne("InfraOps.Domain.Inventory.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplate", "PreventiveTemplate")
                        .WithMany()
                        .HasForeignKey("PreventiveTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("PreventiveTemplate");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionAnswer", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecution", null)
                        .WithMany("Answers")
                        .HasForeignKey("PreventiveExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateItem", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateSection", null)
                        .WithMany("ChecklistItems")
                        .HasForeignKey("PreventiveExecutionTemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateOption", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateItem", null)
                        .WithMany("Options")
                        .HasForeignKey("PreventiveExecutionTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateSection", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecution", null)
                        .WithMany("TemplateSections")
                        .HasForeignKey("PreventiveExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveValidationRecord", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecution", null)
                        .WithMany("ValidationRecords")
                        .HasForeignKey("PreventiveExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveChecklistItem", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplateSection", null)
                        .WithMany("ChecklistItems")
                        .HasForeignKey("PreventiveTemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveChecklistOption", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveChecklistItem", null)
                        .WithMany("Options")
                        .HasForeignKey("PreventiveChecklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplate", b =>
                {
                    b.HasOne("InfraOps.Domain.EntityTypes.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplateSection", b =>
                {
                    b.HasOne("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplate", null)
                        .WithMany("Sections")
                        .HasForeignKey("PreventiveTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityFieldDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("InfraOps.Domain.EntityTypes.Entities.EntityType", b =>
                {
                    b.Navigation("FieldDefinitions");
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("InfraOps.Domain.Identity.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InfraOps.Domain.Inventory.Entities.InventoryItem", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecution", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("TemplateSections");

                    b.Navigation("ValidationRecords");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateItem", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveExecutions.Entities.PreventiveExecutionTemplateSection", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveChecklistItem", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplate", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("InfraOps.Domain.PreventiveTemplates.Entities.PreventiveTemplateSection", b =>
                {
                    b.Navigation("ChecklistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
