namespace InfraOps.Infrastructure.Persistence.Seeding;

public sealed record DemoSeedLabels(
    string UpsName,
    string UpsDescription,
    string GeneratorName,
    string GeneratorDescription,
    string HvacName,
    string HvacDescription,
    string SerialNumberLabel,
    string ManufacturerLabel,
    string ModelLabel,
    string SerialNumberHelpText,
    string UpsTemplateName,
    string UpsTemplateDescription,
    string GeneratorTemplateName,
    string GeneratorTemplateDescription,
    string HvacTemplateName,
    string HvacTemplateDescription,
    string VisualInspectionSection,
    string OperationalReadingsSection,
    string EquipmentCleanQuestion,
    string ActiveAlarmQuestion,
    string OperatingReadingQuestion,
    string OperatingReadingHelpText,
    string OverallConditionQuestion,
    string GoodOption,
    string WarningOption,
    string CriticalOption,
    string AlarmConditionComment,
    string ReadingsAcceptedComment,
    string GeneratorRejectedComment,
    string HvacReworkComment,
    string HvacApprovedComment)
{
    public static DemoSeedLabels ForLocale(string? locale)
    {
        return string.Equals(locale, "pt-BR", StringComparison.OrdinalIgnoreCase)
            ? PortugueseBrazil
            : English;
    }

    public static DemoSeedLabels English { get; } = new(
        "UPS",
        "Uninterruptible power supply systems.",
        "Generator",
        "Standby electrical generation assets.",
        "HVAC",
        "Operational cooling and ventilation assets.",
        "Serial Number",
        "Manufacturer",
        "Model",
        "Manufacturer serial number.",
        "Quarterly UPS Inspection",
        "Power quality and battery inspection.",
        "Monthly Generator Run",
        "Readiness run and visual inspection.",
        "Monthly HVAC Inspection",
        "Cooling performance and equipment condition.",
        "Visual Inspection",
        "Operational Readings",
        "Equipment clean?",
        "Any active alarm?",
        "Primary operating reading",
        "Use the normal operating unit for this asset.",
        "Overall condition",
        "Good",
        "Warning",
        "Critical",
        "Alarm condition observed during inspection.",
        "Readings accepted.",
        "Generator failed load-transfer criteria.",
        "Clarify alarm comment and retake readings.",
        "Cooling checks reviewed.");

    public static DemoSeedLabels PortugueseBrazil { get; } = new(
        "UPS",
        "Sistemas de fornecimento ininterrupto de energia.",
        "Gerador",
        "Ativos de geração elétrica de reserva.",
        "HVAC",
        "Ativos operacionais de refrigeração e ventilação.",
        "Número de série",
        "Fabricante",
        "Modelo",
        "Número de série do fabricante.",
        "Inspeção trimestral de UPS",
        "Inspeção de qualidade de energia e bateria.",
        "Teste mensal do gerador",
        "Teste de prontidão e inspeção visual.",
        "Inspeção mensal de HVAC",
        "Desempenho de refrigeração e condição do equipamento.",
        "Inspeção visual",
        "Leituras operacionais",
        "Equipamento limpo?",
        "Existe alarme ativo?",
        "Leitura operacional principal",
        "Use a unidade operacional normal para este ativo.",
        "Condição geral",
        "Bom",
        "Atenção",
        "Crítico",
        "Condição de alarme observada durante a inspeção.",
        "Leituras aceitas.",
        "O gerador falhou nos critérios de transferência de carga.",
        "Esclareça o comentário do alarme e refaça as leituras.",
        "Verificações de refrigeração revisadas.");
}
